### PR TITLE
Several improvements

### PR DESCRIPTION
**Pull request by mauritsvanrees**
Thanks for this script! A Plone 3.3 database of 36 GB is now reduced to 15 GB when keeping 10 versions, which I will do on production, and 6.5 GB when keeping only 2 for development. :-)

I have made several improvements. See the `HISTORY.rst` file.

I don't know if you are still interested in this script, but I at least wanted to make these changes available.

### CODE REVIEW

**Comment by keul** [comment]
Thank you @mauritsvanrees, all of the changes seems legit to me (and yes, I'm still using it sometimes)!

Unluckily I don't have write permission anymore on RedTurtle repositories and I don't know if anybody is monitoring this package.

@cekk, @ale-rt ?

**Comment by ale-rt** [comment]
Thanks @mauritsvanrees and @keul !
Awesome work!
I would move this repo to collective if you do not mind

**Comment by mauritsvanrees** [comment]
Moving (or copying) to collective seems good to me.

**Comment by ale-rt** [comment]
Here we are :)

**Comment by mauritsvanrees** [comment]
Cool, thanks. :-)

**Pull request merged**
